import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ExportPdfOptions {
  title: string;
  filename: string;
  generatedBy: string;
  columns: string[];
  data: string[][];
}

export const exportToPdf = ({
  title,
  filename,
  generatedBy,
  columns,
  data,
}: ExportPdfOptions) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // --- Header ---
  // Logo (Text substitute for now, assuming logo.svg might be tricky to load reliably in strict environment)
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(title || "App Report", 14, 20);

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(title, 14, 30);

  // Date in Header? User asked for Date in Footer.
  // We can draw a line
  doc.setLineWidth(0.5);
  doc.line(14, 35, pageWidth - 14, 35);

  // --- Table ---
  autoTable(doc, {
    startY: 40,
    head: [columns],
    body: data,
    styles: { fontSize: 10 },
    headStyles: { fillColor: [41, 128, 185] }, // Example blue color
    margin: { top: 40, bottom: 30 },
    didDrawPage: () => {
      // Logic for repetitive header if needed (autoTable handles it)
    },
  });

  // --- Footer ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setFontSize(8);
    doc.setTextColor(100);

    const now = format(new Date(), "dd/MM/yyyy HH:mm");
    const footerY = pageHeight - 10;

    // Left: Generated By
    doc.text(`Generado por: ${generatedBy}`, 14, footerY);

    // Center: Date
    // doc.text(`Fecha: ${now}`, pageWidth / 2, footerY, { align: "center" });
    // Let's put date next to generated by or separate?
    // User: "Quien genero el reporte, fecha y hora del reporte, pagina X de X"

    const footerText = `Generado por: ${generatedBy} | Fecha: ${now}`;
    doc.text(footerText, 14, footerY);

    // Right: Page X of Y
    doc.text(`Página ${i} de ${pageCount}`, pageWidth - 14, footerY, {
      align: "right",
    });
  }

  doc.save(`${filename}_${format(new Date(), "yyyyMMdd_HHmm")}.pdf`);
};

import ExcelJS from "exceljs";

export const exportToExcel = async ({
  title,
  filename,
  generatedBy,
  columns,
  data,
}: ExportPdfOptions) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Reporte");

  // Add Title
  worksheet.mergeCells("A1:F1");
  const titleCell = worksheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { size: 16, bold: true };
  titleCell.alignment = { horizontal: "center" };

  // Add Metadata
  worksheet.mergeCells("A2:F2");
  const metaCell = worksheet.getCell("A2");
  const now = format(new Date(), "dd/MM/yyyy HH:mm");
  metaCell.value = `Generado por: ${generatedBy} | Fecha: ${now}`;
  metaCell.font = { size: 10, italic: true };
  metaCell.alignment = { horizontal: "center" };

  // Add Empty Row
  worksheet.addRow([]);

  // Add Headers
  const headerRow = worksheet.addRow(columns);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF2980B9" },
    };
    cell.alignment = { horizontal: "center" };
  });

  // Add Data
  data.forEach((row) => {
    worksheet.addRow(row);
  });

  // Auto-fit columns
  worksheet.columns.forEach((column) => {
    let maxLength = 0;
    column.eachCell?.({ includeEmpty: true }, (cell) => {
      const columnLength = cell.value ? cell.value.toString().length : 10;
      if (columnLength > maxLength) {
        maxLength = columnLength;
      }
    });
    column.width = maxLength < 10 ? 10 : maxLength + 2;
  });

  // Write Buffer
  const buffer = await workbook.xlsx.writeBuffer();

  // Create Blob and Download
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}_${format(new Date(), "yyyyMMdd_HHmm")}.xlsx`;
  link.click();
  URL.revokeObjectURL(link.href);
};
